### ISSUE TITLE
hello all

### ISSUE THREAD

**Issue by IngenicC** [boundarydevices/android_device_boundary#6] opened 2017-06-21 12:08 UTC

**Comment by gibsson** [comment] 2017-06-26 13:49
Hi,

Which platform are you using? Can you verify that the prebuilt image we provide works fine on Boundary Device reference platforms:
https://boundarydevices.com/android-nougat-7-1-1-release-imx6-boards/

Regards,
Gary

**Comment by gibsson** [comment] 2017-06-30 08:32
Hi,

Since there's no update on this, I close the issue as we can't reproduce here.

Regards,
Gary

**Closed as completed by gibsson** 2017-06-30 08:32 UTC
